controller_list:
  - name: fake_g1_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses per group
  - group: g1
    pose: d1