<robot name="my_base" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 封装变量、常量 -->
    <!-- PI 值设置精度需要高一些，否则后续车轮翻转量计算时，可能会出现肉眼不能察觉的车轮倾斜，从而导致模型抖动 -->
    <xacro:property name="PI" value="3.1415926"/>
    <!-- 宏:黑色设置 -->
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>
    <!-- 底盘属性 -->
    <xacro:property name="base_link_radius" value="0.5" /> <!-- base_link 半径 -->
    <xacro:property name="base_link_length" value="0.02" /> <!-- base_link 长 -->
    <xacro:property name="base_link_m" value="0.5" /> <!-- 质量  -->
    <!-- world -->
    <link name="world"/>

    <link name="base_link">
      <visual>
        <geometry>
          <mesh filename="package://demo02_urdf_gazebo/stl/link_ground.STL"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
        <material name="yellow">
          <color rgba="0.5 0.3 0.0 0.5" />
        </material>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://demo02_urdf_gazebo/stl/link_ground.STL"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
      </collision>
      <inertial>
        <origin xyz="0.039 0 0.055" />
        <mass value="8.050" />
        <!--<inertia ixx="69.167" ixy="0" ixz="-0.533" iyy="76.187" iyz="0" izz="119.082" />-->
        <inertia ixx="0.069167" ixy="0" ixz="0" iyy="0.076187" iyz="0" izz="0.119082" />
      </inertial>

    </link>


    <joint name="base_link2base_footprint" type="fixed">
      <parent link="world" />
      <child link="base_link" />
      <origin xyz="0 0 ${base_link_length / 2 }" />
    </joint>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

</robot>
