mycar:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    
    pid_gains:
      joint1:   
        p: 800.0
        i: 0.01
        d: 100
      joint2:
        p: 10000.0
        i: 0.01
        d: 400
      joint3:   
        p: 1000.0
        i: 0.01
        d: 100
      joint4:  
        p: 100.0
        i: 0.01
        d: 10 
      joint5:   
        p: 100.0
        i: 0.01
        d: 10
      joint6:   
        p: 30.0
        i: 0.01
        d: 1